name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install .NET Framework 4.7.2 SDK
      uses: warrenbuckley/Setup-NET@v1
      with:
        useDotNet: '4.7.2'
        includePrerelease: true

    - name: Build the project
      run: |
        GraphAWSJsonData.sln
      working-directory: $PWD
